### ISSUE TITLE
First public version

### ISSUE THREAD

**Issue by dalf** [searxng/searx-space#13]
Which issues block a first public release:
- [ ] https://github.com/dalf/searx-stats2/issues/9 : it will take some time to rewrite the code.
- [x] https://github.com/dalf/searx-stats2/issues/10 : the https grade is not realiable for now. Being one the first sort criteria, I think it is important to fix this one.
- [x] https://github.com/dalf/searx-stats2/issues/6 : solved by https://github.com/dalf/searx-stats2/pull/11
- [x] https://github.com/dalf/searx-stats2/issues/7: move list of searx-instances from searx to searx-stats2
- [x] Meta-searx instances: add a new file to the [searx-instances](https://github.com/dalf/searx-instances/) project ?
- [x] Should the Searx instances mailing list be referenced ?

**Comment by dalf** [comment]
I have added two new items:
* meta searx instances.
* the mailing list.
